### ISSUE TITLE
no need to use Upgrade-Insecure-Requests  + sec- headers, let it default

### ISSUE THREAD

**Issue by aallali** [issamoxix/BerlinRentMonitoring#1]
dont patch those headers let the default one to be sent, the configs are default, if ever the server side changed rules of how they are being handled, you may get Blocked
https://www.zenrows.com/blog/web-scraping-headers#sec-fetch

for Upgrade-Insecure-Requests if ever ur scrapper had issues with SSL it may cause u problems in scrapping so just drop it

**Comment by issamoxix** [comment]
Thanks for the advise i removed those headers
